### PR TITLE
Remove stubs

### PR DESCRIPTION
**Pull request by staabm**
I wonder why we need these stubs?

it seems they are not referenced anywhere.. and tests don't fail if we delete them?

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Legacy:) thank you

**Comment by staabm** [comment]
Cool. Could you create a release? 

The stubs existance makes some apps of mine mixing up the classes - because of ugly autoloading rules on my end :-)

**Comment by TomasVotruba** [comment]
They should never be part of release.

**Comment by staabm** [comment]
yeah, but they are contained in the current 2.0.0 release.

see https://github.com/FriendsOfREDAXO/rexstan/tree/main/vendor/rector/type-perfect

btw: the release also contains a [phpstan-for-tests.neon](https://github.com/FriendsOfREDAXO/rexstan/blob/main/vendor/rector/type-perfect/phpstan-for-tests.neon) in the project root

**Comment by TomasVotruba** [comment]
Yea, that should not happen 😂

**Pull request merged**
