### PR TITLE
[Rules] Skip enum on NarrowPublicClassMethodParamTypeRule

### LINKED ISSUE #8: Enum cases reported
When only single enum case is passed, it gets reported. That is obviously not possible to typehint:

```txt
Parameter 4 should use "ShipMonk\Warehouse\PickToLight\Enum\SkipPickReason::BarcodeIssue" type as the only type passed to this method 
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/type-perfect/issues/8

### CODE REVIEW

**Comment by samsonasik** [comment]
@janedbal I can't reproduce issue https://github.com/rectorphp/type-perfect/issues/8 by this test, could you verify if something missing in the test? Thank you.

**Comment by janedbal** [comment]
I dont see that call `SkipEnum->skip(PickReasonEnum::BarcodeIssue)` in there.

**Comment by samsonasik** [comment]
I tried and seems still working, could you create a failing test case PR? Thank you.

**Comment by janedbal** [comment]
Sorry, I dont think I'll spend more time with this package as I didnt find it useful for us. I just reported invalid stuff I saw in the output. If you feel I mis-reported, feel free to close this. But this one occurred multiple times.

**Comment by samsonasik** [comment]
Ok, I am closing it as I can't reproduce it, feel free to create a failing test case PR when you have time ;)

**Comment by samsonasik** [comment]
I see, I should add test to `NarrowPublicClassMethodParamTypeRule`

**Comment by samsonasik** [comment]
updated test https://github.com/rectorphp/type-perfect/pull/19/commits/d88d2892c83685a33e07dc4ed87e677a19da542c

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Pull request merged**
