### PR TITLE
Remove phpstan-for-tests.neon from releases

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by staabm** [comment]
@samsonasik any chance to get this merged and a new release?

**Review by samsonasik — APPROVED** [review]

**Comment by staabm** [comment]
thanks!

**Comment by samsonasik** [comment]
2.0.1 just tagged https://github.com/rectorphp/type-perfect/releases/tag/2.0.1

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
